// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOTqM1fcy6d1uHS_k2KR6S8SsnI2t9F4M',
    appId: '1:193456457042:web:2f2450479200c89638268b',
    messagingSenderId: '193456457042',
    projectId: 'connect-ed-dfbbd',
    authDomain: 'connect-ed-dfbbd.firebaseapp.com',
    storageBucket: 'connect-ed-dfbbd.firebasestorage.app',
    measurementId: 'G-S7KTT35TZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5k2SONaLw-uvPV1w4i1wpWHadw4Ppf5Y',
    appId: '1:193456457042:android:93e686c748ca5ae838268b',
    messagingSenderId: '193456457042',
    projectId: 'connect-ed-dfbbd',
    storageBucket: 'connect-ed-dfbbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4S1xP9vxJ9yL7WeqkpHPkbodTGmhGYgE',
    appId: '1:193456457042:ios:3e05e60a182a512138268b',
    messagingSenderId: '193456457042',
    projectId: 'connect-ed-dfbbd',
    storageBucket: 'connect-ed-dfbbd.firebasestorage.app',
    iosBundleId: 'com.example.connectEd2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4S1xP9vxJ9yL7WeqkpHPkbodTGmhGYgE',
    appId: '1:193456457042:ios:3e05e60a182a512138268b',
    messagingSenderId: '193456457042',
    projectId: 'connect-ed-dfbbd',
    storageBucket: 'connect-ed-dfbbd.firebasestorage.app',
    iosBundleId: 'com.example.connectEd2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOTqM1fcy6d1uHS_k2KR6S8SsnI2t9F4M',
    appId: '1:193456457042:web:94176f8200a6c01b38268b',
    messagingSenderId: '193456457042',
    projectId: 'connect-ed-dfbbd',
    authDomain: 'connect-ed-dfbbd.firebaseapp.com',
    storageBucket: 'connect-ed-dfbbd.firebasestorage.app',
    measurementId: 'G-6YR61RY7YW',
  );
}
